### ISSUE TITLE
type class/multiple dispatch

### ISSUE THREAD

**Issue by zaoqi** [lambda-11235/ttyped#1]

**Comment by lambda-11235** [comment]
Not sure what this issue is supposed to be. Could you add a description? @zaoqi

**Comment by lambda-11235** [comment]
If this is about implementing type classes, the core CoC alone provides enough to implement them explicitly.

For monad's you could define
```
let monad = \m : (* -> *). pairT (@a : *. a -> (m a)) (@a : *. @b : *. (m a) -> (a -> (m b)) -> (m b))

let return = \m : (* -> *). \d : (monad m). d (@a : *. a -> (m a)) (\r : (@a : *. a -> (m a)). \b : (@a : *. @b : *. (m a) -> (a -> (m b)) -> (m b)). r)

let bind = \m : (* -> *). \d : (monad m). d (@a : *. @b : *. (m a) -> (a -> (m b)) -> (m b)) (\r : (@a : *. a -> (m a)). \b : (@a : *. @b : *. (m a) -> (a -> (m b)) -> (m b)). b)
```

We could then write a function that, for example, returns the monad containing 0.
```
\m : (* -> *). \d : (monad m). ret (m nat) (return m d nat zero)
```

Note: I use `d` as a reference to `dictionary`, as this implementation views type classes as a dictionary of functions indexed by a type.

**Comment by lambda-11235** [comment]
Closing this issue for now due to lack of a description and the fact that type classes can already be encoded.
